Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.provider "virtualbox" do |v|
		v.name = "SDSW-postgresql"
		v.memory = 512
		v.cpus = 1
	end
	config.vm.hostname = "SDSW-postgresql"
	config.vm.provision :shell, path: "bootstrap.sh"
end
